option(USE_SANITIZERS "Enable sanitizers" OFF)
set(SANITIZERS "" CACHE STRING "Comma-separated list of sanitizers to enable (e.g., address,undefined,thread,memory)")

if (USE_SANITIZERS)
    message(STATUS "[Sanitizers] Requested: ${SANITIZERS}")

    string(REPLACE "," ";" SANITIZER_LIST "${SANITIZERS}")

    set(SAN_ADDRESS_FOUND OFF)
    set(SAN_THREAD_FOUND OFF)
    set(SAN_MEMORY_FOUND OFF)

    foreach(s IN LISTS SANITIZER_LIST)
        if(s STREQUAL "address")
            set(SAN_ADDRESS_FOUND ON)
        elseif(s STREQUAL "thread")
            set(SAN_THREAD_FOUND ON)
        elseif(s STREQUAL "memory")
            set(SAN_MEMORY_FOUND ON)
        endif()
    endforeach()

    # Sanity checks
    if(SAN_ADDRESS_FOUND AND (SAN_THREAD_FOUND OR SAN_MEMORY_FOUND))
        message(FATAL_ERROR "[Sanitizers] 'address' cannot be combined with 'thread' or 'memory'")
    elseif(SAN_THREAD_FOUND AND SAN_MEMORY_FOUND)
        message(FATAL_ERROR "[Sanitizers] 'thread' cannot be combined with 'memory'")
    endif()

    # Compiler-specific
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        foreach(sanitizer IN LISTS SANITIZER_LIST)
            if(sanitizer STREQUAL "memory")
                if(NOT (CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64"))
                    message(FATAL_ERROR "[Sanitizers] 'memory' only supported on Linux x86_64")
                endif()
                add_compile_options(-fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer -g)
                add_link_options(-fsanitize=memory -fno-omit-frame-pointer)
            elseif(sanitizer STREQUAL "thread")
                if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
                    message(FATAL_ERROR "[Sanitizers] 'thread' only supported on Linux")
                endif()
                add_compile_options(-fsanitize=thread -fno-omit-frame-pointer -g)
                add_link_options(-fsanitize=thread -fno-omit-frame-pointer)
            else()
                add_compile_options(-fsanitize=${sanitizer} -fno-omit-frame-pointer -g)
                add_link_options(-fsanitize=${sanitizer} -fno-omit-frame-pointer)
            endif()
        endforeach()

    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC" OR CMAKE_CXX_SIMULATE_ID STREQUAL "MSVC")
        if("address" IN_LIST SANITIZER_LIST)
            message(STATUS "[Sanitizers] Enabling MSVC AddressSanitizer")
            add_compile_options(/fsanitize=address /Zi /Od)
            add_link_options(/INCREMENTAL:NO /fsanitize=address)
        else()
            message(FATAL_ERROR "[Sanitizers] Only 'address' is supported for MSVC/Clang-CL")
        endif()
    endif()
endif()